name: mesh2ssm
channels:
  - iopath
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.8=h166bdaf_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb9d737c_3
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - attrs=22.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py39he91dace_3
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=pyhd8ed1ab_0
  - cudatoolkit=11.5.1=h59c8dcf_11
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.6.6=py39h227be39_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=h27087fc_0
  - fftw=3.3.10=nompi_hf0379b8_106
  - flit-core=3.8.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=hc2a2eb6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=hca18f0e_1
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - gettext=0.21.1=h27087fc_0
  - glib=2.74.1=h6239696_1
  - glib-tools=2.74.1=h6239696_1
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.21.3=h4243ec0_1
  - gstreamer=1.21.3=h25f0c4b_1
  - gstreamer-orc=0.4.33=h166bdaf_0
  - harfbuzz=6.0.0=h8e241bc_0
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_resources=5.10.2=pyhd8ed1ab_0
  - iopath=0.1.9=py39
  - ipykernel=6.20.2=pyh210e3f2_0
  - ipython=8.8.0=pyh41d4057_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.4=pyhd8ed1ab_0
  - jack=1.9.21=h583fa2b_2
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h166bdaf_2
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter=1.0.0=py39hf3d152e_8
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_console=6.4.4=pyhd8ed1ab_0
  - jupyter_core=5.1.5=py39hf3d152e_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.1.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.5=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.14=hfd0df8a_1
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_openblas
  - libcap=2.66=ha37c62d_0
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=15.0.7=default_had23c3d_0
  - libclang13=15.0.7=default_h3e3d535_0
  - libcups=2.3.3=h36d4200_3
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.10=h28343ad_4
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.2=h27087fc_0
  - libgcc-ng=12.2.0=h65d4601_19
  - libgcrypt=1.10.1=h166bdaf_0
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.74.1=h606061b_1
  - libgomp=12.2.0=h65d4601_19
  - libgpg-error=1.46=h620e276_0
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.4=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - libllvm15=15.0.7=hadd5161_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h753d276_0
  - libpq=15.1=hb675445_3
  - libsndfile=1.2.0=hb75c966_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.40.0=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libsystemd0=252=h2a991cd_0
  - libtiff=4.5.0=h6adf6a1_2
  - libtool=2.4.7=h27087fc_0
  - libudev1=252=h166bdaf_0
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.10.3=h7463322_0
  - libzlib=1.2.13=h166bdaf_4
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.1.2=py39h72bdee0_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - mpg123=1.31.2=hcb278e6_0
  - mysql-common=8.0.32=ha901b37_0
  - mysql-libs=8.0.32=hd7da12d_0
  - nbclassic=0.4.8=pyhd8ed1ab_0
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert=7.2.9=pyhd8ed1ab_0
  - nbconvert-core=7.2.9=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.9=pyhd8ed1ab_0
  - nbformat=5.7.3=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - notebook=6.5.2=pyha770c72_1
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.82=he02c5a1_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.0.7=h0b41bf4_1
  - packaging=23.0=pyhd8ed1ab_0
  - pandoc=2.19.2=h32600fe_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py39ha08a7e4_0
  - pip=22.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.6.2=pyhd8ed1ab_0
  - ply=3.11=py_1
  - portalocker=2.7.0=py39hf3d152e_0
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - prompt_toolkit=3.0.36=hd8ed1ab_0
  - psutil=5.9.4=py39hb9d737c_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio=16.1=ha8d29e2_1
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyqt=5.15.7=py39h5c7b992_3
  - pyqt5-sip=12.11.0=py39h227be39_3
  - pyrsistent=0.19.3=py39h72bdee0_0
  - python=3.9.15=hba424b6_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-json-logger=2.0.4=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pyyaml=6.0=py39hb9d737c_5
  - pyzmq=25.0.0=py39h0be026e_0
  - qt-main=5.15.6=h602db52_6
  - qtconsole=5.4.0=pyhd8ed1ab_0
  - qtconsole-base=5.4.0=pyha770c72_0
  - qtpy=2.3.0=pyhd8ed1ab_0
  - readline=8.1.2=h0f457ee_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=66.1.1=pyhd8ed1ab_0
  - sip=6.7.5=py39h5a03fae_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - termcolor=2.2.0=pyhd8ed1ab_0
  - terminado=0.17.1=pyh41d4057_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.2=py39hb9d737c_1
  - traitlets=5.8.1=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.2=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - widgetsnbextension=4.0.5=pyhd8ed1ab_0
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.11.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
  - pip:
    - absl-py==1.4.0
    - alembic==1.9.2
    - autopage==0.5.1
    - black==22.12.0
    - cachetools==5.3.0
    - chamfer-distance==0.1
    - charset-normalizer==3.0.1
    - click==8.1.3
    - cliff==4.1.0
    - cmaes==0.9.1
    - cmd2==2.4.2
    - colorlog==6.7.0
    - contourpy==1.0.7
    - cycler==0.11.0
    - cython==0.29.33
    - flake8==6.0.0
    - flake8-bugbear==23.1.20
    - flake8-comprehensions==3.10.1
    - fonttools==4.38.0
    - gdist==2.1.0
    - google-auth==2.16.1
    - google-auth-oauthlib==0.4.6
    - greenlet==2.0.1
    - grpcio==1.51.3
    - imageio==2.25.0
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - libcst==0.4.9
    - mako==1.2.4
    - markdown==3.4.1
    - matplotlib==3.6.3
    - mccabe==0.7.0
    - moreorless==0.4.0
    - mpmath==1.2.1
    - mypy-extensions==0.4.3
    - networkx==2.6.3
    - ninja==1.11.1
    - numpy==1.22.4
    - oauthlib==3.2.2
    - opencv-python==4.7.0.68
    - openmesh==1.2.1
    - optuna==2.10.0
    - pathspec==0.10.3
    - pbr==5.11.1
    - plotly==5.13.0
    - point-cloud-utils==0.29.1
    - pooch==1.7.0
    - prettytable==3.6.0
    - protobuf==3.20.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.10.0
    - pyflakes==3.0.1
    - pyg-lib==0.1.0+pt111cu115
    - pymeshlab==2021.10
    - pyparsing==3.0.9
    - pyperclip==1.8.2
    - pypoisson==0.10
    - pytorch3d==0.7.2
    - pyvista==0.38.3
    - pywavelets==1.4.1
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - rtree==0.9.7
    - scikit-image==0.19.3
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - scooby==0.7.1
    - split-folders==0.5.1
    - sqlalchemy==1.4.46
    - stdlibs==2022.10.9
    - stevedore==4.1.1
    - sympy==1.11.1
    - tenacity==8.1.0
    - tensorboard==2.12.0
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - tifffile==2023.1.23.1
    - tomli==2.0.1
    - torch==1.11.0+cu115
    - torch-cluster==1.6.0
    - torch-geometric==2.2.0
    - torch-scatter==2.1.0
    - torch-sparse==0.6.16
    - torch-spline-conv==1.2.1
    - torch-summary==1.4.5
    - torchaudio==0.11.0+cu115
    - torchdiffeq==0.2.3
    - torchvision==0.12.0+cu115
    - tqdm==4.62.0
    - trailrunner==1.2.1
    - trimesh==3.10.1
    - typing-inspect==0.8.0
    - urllib3==1.26.14
    - usort==1.0.5
    - vtk==9.2.6
    - werkzeug==2.2.3
prefix: /home/sci/iyerkrithika/miniconda3/envs/mesh2ssm
